image: Visual Studio 2015

init:
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio "%VSVER%".0\VC\vcvarsall.bat" %ARCH%

environment:
  PATH: '%PATH%;%QTDIR%\bin'
  matrix:
    - QTDIR: C:\Qt\5.6\msvc2013
      VSVER: 12
      ARCH: x86
    - QTDIR: C:\Qt\5.9\msvc2013_64
      VSVER: 12
      ARCH: x64

build_script:
  - cmd: qmake qtpromise.pro
  - cmd: nmake

test_script:
  - cmd: nmake check

